# Generated by Django 6.0.3 on 2026-03-25 14:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0002_incident_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='verified',
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='roadstatus',
            name='effective_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When does this status take effect'),
        ),
        migrations.AlterField(
            model_name='roadstatus',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('diversion', 'Diversion'), ('construction', 'Under Construction'), ('partially_open', 'Partially Open')], default='open', max_length=20),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('commuter', 'Commuter'), ('police', 'Traffic Police (Staff)'), ('engineer', 'Road Engineer')], default='commuter', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
